{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
{{ if .Values.ingress.tls}}
    cert-manager.io/cluster-issuer: "cert-manager-global"
    kubernetes.io/ingress.allow-http: "false"
{{ end }}

spec:
{{ if .Values.ingress.tls}}
  tls:
  - secretName: cert-manager-private-key
    hosts:
    - {{ .Values.baseUrl }}
{{ end }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: k8s-on-demand-provisioner
          servicePort: 3000
{{ if .Values.ingress.tls}}
    host: {{ .Values.baseUrl }}
{{ end }}
{{ end }}
